In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np

### Generate Synthetic Data

In [3]:
from utils import generate_synthetic_data

N = 10000
corr_strength = 0.8
class_balance = [0.5, 0.5]
cond_probs = np.array([[0.5, 0.4, 0.1], [0.5, 0.1, 0.4]])
corr_graph = [{0, 1, 4}, {2}, {3}, {5}, {6}]

y_true, L = generate_synthetic_data(N, corr_strength, class_balance, cond_probs, corr_graph)
print(L)

[[-1 -1  1 ... -1  1  1]
 [-1 -1  0 ... -1 -1  0]
 [-1 -1  0 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1  0]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1  1 ... -1  0  1]]


### Learn Dependencies between Labeling Functions

In [6]:
from learn_deps import learn_structure, get_deps_from_inverse_sig

J_hat = learn_structure(L)
deps_hat = get_deps_from_inverse_sig(J_hat, thresh=1.5)

#remove repeated edges
deps = []
for i,j in deps_hat:
    if i < j:
        deps.append((i,j))

print("Learned dependencies: ", deps) #should be [(0,1), (0,4), (1,4)]

Variable var344: value [[ 5.12403281e+00 -2.19461446e+00 -2.85294490e-02 -1.09085369e-02
  -2.34785244e+00 -3.23359906e-02 -2.06795853e-02]
 [-2.19461446e+00  5.20306635e+00 -5.83568520e-03 -1.56106507e-02
  -2.45538304e+00 -5.29613392e-02 -1.33855314e-02]
 [-2.85294490e-02 -5.83568520e-03  1.48110981e+00  8.67368303e-03
  -1.69984893e-02 -7.32106712e-02 -5.27144421e-03]
 [-1.09085369e-02 -1.56106507e-02  8.67368303e-03  1.45742213e+00
  -4.51783357e-02 -7.20493699e-02 -2.52434321e-02]
 [-2.34785244e+00 -2.45538304e+00 -1.69984893e-02 -4.51783357e-02
   5.35332047e+00  3.77938357e-02 -1.87122786e-02]
 [-3.23359906e-02 -5.29613392e-02 -7.32106712e-02 -7.20493699e-02
   3.77938357e-02  1.45902343e+00 -2.07311520e-02]
 [-2.06795853e-02 -1.33855314e-02 -5.27144421e-03 -2.52434321e-02
  -1.87122786e-02 -2.07311520e-02  1.44853501e+00]]
Variable var343: value [[ 5.12403243e+00 -2.19461487e+00 -2.85294128e-02 -1.09084916e-02
  -2.34785266e+00 -3.23358089e-02 -2.06795576e-02]
 [-2.19461487e+00

/home/kaustubh-anaconda/anaconda3/envs/snorkel_env_spouse/lib/python3.6/site-packages/cvxpy/expressions/expression.py:516: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
